name: Delete Workflows

on:
  workflow_dispatch:  # 수동 실행 전용

permissions:
  contents: write
  actions: write

jobs:
  delete_workflow_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Find Workflow Files
        id: find_files
        run: |
          files=$(find .github/workflows -type f \( -name "*.yml" -o -name "*.yaml" \))
          echo "FOUND_FILES<<EOF" >> $GITHUB_ENV
          echo "$files" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "$files" > deleted.txt
          cat deleted.txt

      - name: Delete Workflow Files
        run: |
          while IFS= read -r file; do
            echo "Deleting $file"
            git rm -f "$file"
          done < deleted.txt

      - name: Commit and Push Deletion
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -m "🧹 Delete all workflow files from .github/workflows"
          git push
