name: EthicalCheck-Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  Trigger_EthicalCheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Prepare Output Directory
        run: |
          mkdir -p ./ethicalcheck/output
          chmod -R 755 ./ethicalcheck

      - name: Install JSON Validator (jq)
        run: |
          sudo apt-get update && sudo apt-get install -y jq

      - name: EthicalCheck - Free API Security Testing
        uses: apisec-inc/ethicalcheck-action@005fac321dd843682b1af6b72f30caaf9952c641
        with:
          oas-url: "https://petstore.swagger.io/v2/swagger.json"  # ✅ 여기에 실제 API 명세 JSON URL 사용
          email: "kwonny1302@gmail.com"
          sarif-result-file: "./ethicalcheck/output/ethicalcheck-results.sarif"

      - name: Validate SARIF file
        run: |
          if [ ! -s "./ethicalcheck/output/ethicalcheck-results.sarif" ]; then
            echo "❌ SARIF 파일이 비어 있습니다. 업로드를 중단합니다."
            exit 1
          fi
          if ! jq empty ./ethicalcheck/output/ethicalcheck-results.sarif; then
            echo "❌ SARIF 파일이 올바른 JSON이 아닙니다."
            exit 1
          fi
          echo "✅ SARIF 파일이 유효한 JSON 형식입니다."

      - name: Upload SARIF to GitHub Security Tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ./ethicalcheck/output/ethicalcheck-results.sarif
