name: EthicalCheck-Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '24 13 * * 4'  # 매주 목요일 오후 10:24 (KST 기준)
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  Trigger_EthicalCheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Prepare Directories
        run: |
          mkdir -p ./ethicalcheck/output
          chmod -R 755 ./ethicalcheck
          echo "✅ 디렉토리 생성 및 권한 설정 완료"

      - name: Install Required Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl unzip

      - name: EthicalCheck - Free API Security Testing
        uses: apisec-inc/ethicalcheck-action@005fac321dd843682b1af6b72f30caaf9952c641
        with:
          oas-url: "https://petstore.swagger.io/v2/swagger.json"  # ✅ 실제 API 문서 경로로 교체 가능
          email: "kwonny1302@gmail.com"
          sarif-result-file: "./ethicalcheck/output/ethicalcheck-results.sarif"

      - name: Check SARIF Output
        run: |
          if [ ! -s "./ethicalcheck/output/ethicalcheck-results.sarif" ]; then
            echo "❌ SARIF 파일이 비어있습니다. upload-sarif 생략됨."
            exit 1
          fi
          echo "✅ SARIF 파일이 생성되었습니다."

      - name: Upload SARIF to GitHub Security Tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ./ethicalcheck/output/ethicalcheck-results.sarif
